# Generated by Django 4.2.6 on 2023-10-25 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('IDAlimento', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('RutCliente', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('FechaNacimiento', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=15)),
                ('Direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dietas',
            fields=[
                ('IDDieta', models.AutoField(primary_key=True, serialize=False)),
                ('FechaInicio', models.DateField()),
                ('FechaFin', models.DateField()),
                ('RutCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Dietistas',
            fields=[
                ('RutDietista', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=15)),
                ('Especialidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nutricionistas',
            fields=[
                ('RutNutricionista', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=15)),
                ('Especialidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosDelSistema',
            fields=[
                ('IDUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=255)),
                ('TipoUsuario', models.CharField(choices=[('Cliente', 'Cliente'), ('Nutricionista', 'Nutricionista'), ('Dietista', 'Dietista')], max_length=15)),
                ('RutCliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.clientes')),
                ('RutDietista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.dietistas')),
                ('RutNutricionista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.nutricionistas')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('IDConsulta', models.AutoField(primary_key=True, serialize=False)),
                ('FechaAtencion', models.DateField()),
                ('DescripcionConsulta', models.TextField()),
                ('RutCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionesNutricionales',
            fields=[
                ('IDEvaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('FechaEvaluacion', models.DateField()),
                ('Peso', models.FloatField()),
                ('Altura', models.FloatField()),
                ('IMC', models.FloatField()),
                ('RutCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.clientes')),
                ('RutNutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nutricionistas')),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('IDCita', models.AutoField(primary_key=True, serialize=False)),
                ('FechaCita', models.DateField()),
                ('HoraCita', models.TimeField()),
                ('LugarCita', models.CharField(max_length=100)),
                ('RutCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.clientes')),
                ('RutNutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nutricionistas')),
            ],
        ),
        migrations.CreateModel(
            name='DietasAlimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDAlimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.alimentos')),
                ('IDDieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dietas')),
            ],
            options={
                'unique_together': {('IDDieta', 'IDAlimento')},
            },
        ),
    ]
